services:

  - type: web

    name: anuj-telegram-mini-app

    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: python bot.py

    envVars:

      - key: BOT_TOKEN
        sync: false

      - key: WEB_URL
        sync: false

      - key: CHANNEL_USERNAME
        sync: false
